[2024-07-12T02:22:09.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T02:22:09.422+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-12T01:15:00+00:00 [queued]>
[2024-07-12T02:22:09.426+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-12T01:15:00+00:00 [queued]>
[2024-07-12T02:22:09.426+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-07-12T02:22:09.431+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-12 01:15:00+00:00
[2024-07-12T02:22:09.434+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-12T02:22:09.434+0000] {standard_task_runner.py:63} INFO - Started process 214 to run task
[2024-07-12T02:22:09.434+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-12T01:15:00+00:00', '--job-id', '621', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmp81hfpfqq']
[2024-07-12T02:22:09.435+0000] {standard_task_runner.py:91} INFO - Job 621: Subtask load
[2024-07-12T02:22:09.453+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-12T01:15:00+00:00 [running]> on host af32cf3fdf88
[2024-07-12T02:22:09.578+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T01:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-12T01:15:00+00:00'
[2024-07-12T02:22:09.579+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T02:22:09.584+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-12T02:22:10.113+0000] {logging_mixin.py:188} INFO - Successfully connect to database!
[2024-07-12T02:22:10.557+0000] {logging_mixin.py:188} INFO - Insert time: 0.44240450859069824 seconds
[2024-07-12T02:22:10.560+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-12T02:22:10.561+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T02:22:10.572+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=load, run_id=scheduled__2024-07-12T01:15:00+00:00, execution_date=20240712T011500, start_date=20240712T022209, end_date=20240712T022210
[2024-07-12T02:22:10.609+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-12T02:22:10.624+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T02:22:10.626+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
