[2024-07-05T09:20:36.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T09:20:36.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load manual__2024-07-05T09:20:33.046396+00:00 [queued]>
[2024-07-05T09:20:36.281+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load manual__2024-07-05T09:20:33.046396+00:00 [queued]>
[2024-07-05T09:20:36.281+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-05T09:20:36.289+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-05 09:20:33.046396+00:00
[2024-07-05T09:20:36.296+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=50317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-05T09:20:36.296+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'manual__2024-07-05T09:20:33.046396+00:00', '--job-id', '606', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmprpbii2gy']
[2024-07-05T09:20:36.297+0000] {standard_task_runner.py:63} INFO - Started process 50319 to run task
[2024-07-05T09:20:36.297+0000] {standard_task_runner.py:91} INFO - Job 606: Subtask load
[2024-07-05T09:20:36.326+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load manual__2024-07-05T09:20:33.046396+00:00 [running]> on host 0b64c9d791b9
[2024-07-05T09:20:36.381+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T09:20:33.046396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T09:20:33.046396+00:00'
[2024-07-05T09:20:36.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T09:20:36.522+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-05T09:20:37.504+0000] {logging_mixin.py:188} INFO - Successfully connect to database!
[2024-07-05T09:20:37.904+0000] {logging_mixin.py:188} INFO - Insert time: 0.39981627464294434 seconds
[2024-07-05T09:20:37.906+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-05T09:20:37.908+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T09:20:37.920+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=load, run_id=manual__2024-07-05T09:20:33.046396+00:00, execution_date=20240705T092033, start_date=20240705T092036, end_date=20240705T092037
[2024-07-05T09:20:37.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-05T09:20:37.966+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T09:20:37.969+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
