[2024-07-24T03:15:02.875+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T03:15:02.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-24T02:15:00+00:00 [queued]>
[2024-07-24T03:15:02.894+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-24T02:15:00+00:00 [queued]>
[2024-07-24T03:15:02.894+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-24T03:15:02.901+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-24 02:15:00+00:00
[2024-07-24T03:15:02.906+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=358) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-24T03:15:02.907+0000] {standard_task_runner.py:63} INFO - Started process 360 to run task
[2024-07-24T03:15:02.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-24T02:15:00+00:00', '--job-id', '3364', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmpf4k27rc2']
[2024-07-24T03:15:02.908+0000] {standard_task_runner.py:91} INFO - Job 3364: Subtask load
[2024-07-24T03:15:02.930+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-24T02:15:00+00:00 [running]> on host 54b60780a4fd
[2024-07-24T03:15:02.975+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T02:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T02:15:00+00:00'
[2024-07-24T03:15:02.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T03:15:03.104+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-24T03:15:03.865+0000] {logging_mixin.py:188} INFO - Successfully connect to database!
[2024-07-24T03:15:04.612+0000] {logging_mixin.py:188} INFO - Insert time: 0.7447919845581055 seconds
[2024-07-24T03:15:04.616+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-24T03:15:04.617+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T03:15:04.631+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=load, run_id=scheduled__2024-07-24T02:15:00+00:00, execution_date=20240724T021500, start_date=20240724T031502, end_date=20240724T031504
[2024-07-24T03:15:04.688+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-24T03:15:04.703+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T03:15:04.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
