[2024-07-08T04:59:18.932+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T04:59:18.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load manual__2024-07-08T04:59:15.179764+00:00 [queued]>
[2024-07-08T04:59:18.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load manual__2024-07-08T04:59:15.179764+00:00 [queued]>
[2024-07-08T04:59:18.954+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-08T04:59:18.961+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-08 04:59:15.179764+00:00
[2024-07-08T04:59:18.966+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=69785) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-08T04:59:18.967+0000] {standard_task_runner.py:63} INFO - Started process 69787 to run task
[2024-07-08T04:59:18.966+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'manual__2024-07-08T04:59:15.179764+00:00', '--job-id', '1187', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmp2x33c0ti']
[2024-07-08T04:59:18.967+0000] {standard_task_runner.py:91} INFO - Job 1187: Subtask load
[2024-07-08T04:59:18.992+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load manual__2024-07-08T04:59:15.179764+00:00 [running]> on host 0b64c9d791b9
[2024-07-08T04:59:19.036+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T04:59:15.179764+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T04:59:15.179764+00:00'
[2024-07-08T04:59:19.037+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T04:59:19.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-08T04:59:19.634+0000] {logging_mixin.py:188} INFO - Successfully connect to database!
[2024-07-08T04:59:20.025+0000] {logging_mixin.py:188} INFO - Insert time: 0.3826272487640381 seconds
[2024-07-08T04:59:20.028+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T04:59:20.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T04:59:20.051+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=load, run_id=manual__2024-07-08T04:59:15.179764+00:00, execution_date=20240708T045915, start_date=20240708T045918, end_date=20240708T045920
[2024-07-08T04:59:20.095+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T04:59:20.116+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T04:59:20.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
