[2024-07-03T09:56:33.871+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T09:56:33.889+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.failed_dag manual__2024-07-03T09:56:22.443590+00:00 [queued]>
[2024-07-03T09:56:33.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.failed_dag manual__2024-07-03T09:56:22.443590+00:00 [queued]>
[2024-07-03T09:56:33.894+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-03T09:56:33.900+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): failed_dag> on 2024-07-03 09:56:22.443590+00:00
[2024-07-03T09:56:33.904+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T09:56:33.904+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'failed_dag', 'manual__2024-07-03T09:56:22.443590+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmp7pdo1en2']
[2024-07-03T09:56:33.905+0000] {standard_task_runner.py:63} INFO - Started process 4209 to run task
[2024-07-03T09:56:33.906+0000] {standard_task_runner.py:91} INFO - Job 234: Subtask failed_dag
[2024-07-03T09:56:33.930+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.failed_dag manual__2024-07-03T09:56:22.443590+00:00 [running]> on host 0b64c9d791b9
[2024-07-03T09:56:33.975+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@ponpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='failed_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T09:56:22.443590+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-03T09:56:22.443590+00:00'
[2024-07-03T09:56:33.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T09:56:33.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-03T09:56:34.001+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T09:56:34.002+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fail_dags_monitor.py", line 34, in get_failed_dag
    if run.end_date > (datetime.now(LOCAL_TIMEZONE) - timedelta(minutes=LAST_INTERVAL)):
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta minutes component: InstrumentedAttribute
[2024-07-03T09:56:34.007+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Fail_Dags_Monitor, task_id=failed_dag, run_id=manual__2024-07-03T09:56:22.443590+00:00, execution_date=20240703T095622, start_date=20240703T095633, end_date=20240703T095634
[2024-07-03T09:56:34.012+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 234 for task failed_dag (unsupported type for timedelta minutes component: InstrumentedAttribute; 4209)
[2024-07-03T09:56:34.056+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T09:56:34.066+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T09:56:34.067+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
