[2024-07-07T12:15:03.097+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T12:15:03.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-07T11:15:00+00:00 [queued]>
[2024-07-07T12:15:03.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-07T11:15:00+00:00 [queued]>
[2024-07-07T12:15:03.116+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-07T12:15:03.121+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-07 11:15:00+00:00
[2024-07-07T12:15:03.126+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=57524) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-07T12:15:03.125+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-07T11:15:00+00:00', '--job-id', '947', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmp22km6psr']
[2024-07-07T12:15:03.127+0000] {standard_task_runner.py:63} INFO - Started process 57526 to run task
[2024-07-07T12:15:03.127+0000] {standard_task_runner.py:91} INFO - Job 947: Subtask load
[2024-07-07T12:15:03.152+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-07T11:15:00+00:00 [running]> on host 0b64c9d791b9
[2024-07-07T12:15:03.195+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T11:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T11:15:00+00:00'
[2024-07-07T12:15:03.196+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T12:15:03.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-07T12:15:03.499+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T12:15:03.500+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fail_dags_monitor.py", line 67, in load
    conn = psycopg2.connect(database=DB_NAME,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "athena-uat.cybjleasxg2d.ap-southeast-1.rds.amazonaws.com" to address: Name or service not known

[2024-07-07T12:15:03.511+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Fail_Dags_Monitor, task_id=load, run_id=scheduled__2024-07-07T11:15:00+00:00, execution_date=20240707T111500, start_date=20240707T121503, end_date=20240707T121503
[2024-07-07T12:15:03.520+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 947 for task load (could not translate host name "athena-uat.cybjleasxg2d.ap-southeast-1.rds.amazonaws.com" to address: Name or service not known
; 57526)
[2024-07-07T12:15:03.532+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T12:15:03.545+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T12:15:03.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
