[2024-07-22T01:49:24.344+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T01:49:24.361+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-21T23:15:00+00:00 [queued]>
[2024-07-22T01:49:24.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-21T23:15:00+00:00 [queued]>
[2024-07-22T01:49:24.365+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-22T01:49:24.371+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-21 23:15:00+00:00
[2024-07-22T01:49:24.375+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1486) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-22T01:49:24.376+0000] {standard_task_runner.py:63} INFO - Started process 1488 to run task
[2024-07-22T01:49:24.375+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-21T23:15:00+00:00', '--job-id', '2957', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmptovwesrt']
[2024-07-22T01:49:24.377+0000] {standard_task_runner.py:91} INFO - Job 2957: Subtask load
[2024-07-22T01:49:24.400+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-21T23:15:00+00:00 [running]> on host 159800ebe1e5
[2024-07-22T01:49:24.443+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T23:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-21T23:15:00+00:00'
[2024-07-22T01:49:24.444+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T01:49:24.571+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-22T01:49:24.617+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T01:49:24.617+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fail_dags_monitor.py", line 67, in load
    conn = psycopg2.connect(database=DB_NAME,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "athena-uat.cybjleasxg2d.ap-southeast-1.rds.amazonaws.com" to address: Name or service not known

[2024-07-22T01:49:24.622+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Fail_Dags_Monitor, task_id=load, run_id=scheduled__2024-07-21T23:15:00+00:00, execution_date=20240721T231500, start_date=20240722T014924, end_date=20240722T014924
[2024-07-22T01:49:24.626+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2957 for task load (could not translate host name "athena-uat.cybjleasxg2d.ap-southeast-1.rds.amazonaws.com" to address: Name or service not known
; 1488)
[2024-07-22T01:49:24.654+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T01:49:24.663+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T01:49:24.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
