[2024-07-11T00:32:31.260+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T00:32:31.280+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-10T21:15:00+00:00 [queued]>
[2024-07-11T00:32:31.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-10T21:15:00+00:00 [queued]>
[2024-07-11T00:32:31.286+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-11T00:32:31.294+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-10 21:15:00+00:00
[2024-07-11T00:32:31.299+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-11T00:32:31.300+0000] {standard_task_runner.py:63} INFO - Started process 2210 to run task
[2024-07-11T00:32:31.299+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-10T21:15:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmp1xt9gykg']
[2024-07-11T00:32:31.300+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask load
[2024-07-11T00:32:31.323+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-10T21:15:00+00:00 [running]> on host 469b2f9527f6
[2024-07-11T00:32:31.363+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T21:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-10T21:15:00+00:00'
[2024-07-11T00:32:31.364+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T00:32:31.495+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-11T00:32:41.449+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-11T00:32:41.462+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-11T00:32:41.463+0000] {process_utils.py:132} INFO - Sending 15 to group 2210. PIDs of all processes in the group: [2210]
[2024-07-11T00:32:41.464+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2210
[2024-07-11T00:32:50.640+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-11T00:32:50.678+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2210, status='terminated', exitcode=0, started='00:32:30') (2210) terminated with exit code 0
