[2024-07-09T02:43:14.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T02:43:14.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-08T23:15:00+00:00 [queued]>
[2024-07-09T02:43:14.071+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-08T23:15:00+00:00 [queued]>
[2024-07-09T02:43:14.071+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-07-09T02:43:14.078+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-08 23:15:00+00:00
[2024-07-09T02:43:14.085+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11338) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-09T02:43:14.086+0000] {standard_task_runner.py:63} INFO - Started process 11340 to run task
[2024-07-09T02:43:14.084+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-08T23:15:00+00:00', '--job-id', '2237', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmpi611e3s1']
[2024-07-09T02:43:14.086+0000] {standard_task_runner.py:91} INFO - Job 2237: Subtask load
[2024-07-09T02:43:14.116+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-08T23:15:00+00:00 [running]> on host ec4fc0d2456a
[2024-07-09T02:43:14.183+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T23:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T23:15:00+00:00'
[2024-07-09T02:43:14.185+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T02:43:14.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-09T02:43:15.158+0000] {logging_mixin.py:188} INFO - Successfully connect to database!
[2024-07-09T02:43:15.860+0000] {logging_mixin.py:188} INFO - Insert time: 0.7014420032501221 seconds
[2024-07-09T02:43:15.865+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-09T02:43:15.867+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T02:43:15.883+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=load, run_id=scheduled__2024-07-08T23:15:00+00:00, execution_date=20240708T231500, start_date=20240709T024314, end_date=20240709T024315
[2024-07-09T02:43:15.912+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-09T02:43:15.931+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T02:43:15.935+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
