[2024-07-08T07:18:32.911+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T07:18:32.933+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-06T07:15:00+00:00 [queued]>
[2024-07-08T07:18:32.938+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-06T07:15:00+00:00 [queued]>
[2024-07-08T07:18:32.939+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 7
[2024-07-08T07:18:32.949+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-06 07:15:00+00:00
[2024-07-08T07:18:32.956+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6963) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-08T07:18:32.958+0000] {standard_task_runner.py:63} INFO - Started process 6966 to run task
[2024-07-08T07:18:32.956+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-06T07:15:00+00:00', '--job-id', '1502', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmpt_qw5vl4']
[2024-07-08T07:18:32.958+0000] {standard_task_runner.py:91} INFO - Job 1502: Subtask load
[2024-07-08T07:18:32.995+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-06T07:15:00+00:00 [running]> on host b50f11f07b36
[2024-07-08T07:18:33.049+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T07:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-06T07:15:00+00:00'
[2024-07-08T07:18:33.050+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T07:18:33.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-08T07:18:33.535+0000] {logging_mixin.py:188} INFO - Successfully connect to database!
[2024-07-08T07:18:33.832+0000] {logging_mixin.py:188} INFO - Insert time: 0.2957041263580322 seconds
[2024-07-08T07:18:33.835+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T07:18:33.836+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T07:18:33.847+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=load, run_id=scheduled__2024-07-06T07:15:00+00:00, execution_date=20240706T071500, start_date=20240708T071832, end_date=20240708T071833
[2024-07-08T07:18:33.871+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T07:18:33.892+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T07:18:33.894+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
