[2024-07-10T16:44:46.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T16:44:46.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-10T14:15:00+00:00 [queued]>
[2024-07-10T16:44:46.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-10T14:15:00+00:00 [queued]>
[2024-07-10T16:44:46.272+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-07-10T16:44:46.277+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-10 14:15:00+00:00
[2024-07-10T16:44:46.280+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1820) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-10T16:44:46.281+0000] {standard_task_runner.py:63} INFO - Started process 1822 to run task
[2024-07-10T16:44:46.281+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-10T14:15:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmpuxhid0w7']
[2024-07-10T16:44:46.282+0000] {standard_task_runner.py:91} INFO - Job 106: Subtask load
[2024-07-10T16:44:46.300+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-10T14:15:00+00:00 [running]> on host 469b2f9527f6
[2024-07-10T16:44:46.342+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T14:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-10T14:15:00+00:00'
[2024-07-10T16:44:46.342+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T16:44:46.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-10T16:44:46.511+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T16:44:46.511+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fail_dags_monitor.py", line 67, in load
    conn = psycopg2.connect(database=DB_NAME,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "athena-uat.cybjleasxg2d.ap-southeast-1.rds.amazonaws.com" to address: Name or service not known

[2024-07-10T16:44:46.517+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Fail_Dags_Monitor, task_id=load, run_id=scheduled__2024-07-10T14:15:00+00:00, execution_date=20240710T141500, start_date=20240710T164446, end_date=20240710T164446
[2024-07-10T16:44:46.522+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 106 for task load (could not translate host name "athena-uat.cybjleasxg2d.ap-southeast-1.rds.amazonaws.com" to address: Name or service not known
; 1822)
[2024-07-10T16:44:46.550+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T16:44:46.559+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T16:44:46.560+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
