[2024-07-08T05:04:30.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T05:04:30.083+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load manual__2024-07-08T05:04:25.750731+00:00 [queued]>
[2024-07-08T05:04:30.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load manual__2024-07-08T05:04:25.750731+00:00 [queued]>
[2024-07-08T05:04:30.089+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-08T05:04:30.096+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-08 05:04:25.750731+00:00
[2024-07-08T05:04:30.103+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'manual__2024-07-08T05:04:25.750731+00:00', '--job-id', '1203', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmpia5e6ls2']
[2024-07-08T05:04:30.105+0000] {standard_task_runner.py:91} INFO - Job 1203: Subtask load
[2024-07-08T05:04:30.104+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-08T05:04:30.105+0000] {standard_task_runner.py:63} INFO - Started process 274 to run task
[2024-07-08T05:04:30.131+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load manual__2024-07-08T05:04:25.750731+00:00 [running]> on host b50f11f07b36
[2024-07-08T05:04:30.182+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T05:04:25.750731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T05:04:25.750731+00:00'
[2024-07-08T05:04:30.182+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T05:04:30.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-08T05:04:30.761+0000] {logging_mixin.py:188} INFO - Successfully connect to database!
[2024-07-08T05:04:31.035+0000] {logging_mixin.py:188} INFO - Insert time: 0.2714369297027588 seconds
[2024-07-08T05:04:31.036+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T05:04:31.038+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T05:04:31.049+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=load, run_id=manual__2024-07-08T05:04:25.750731+00:00, execution_date=20240708T050425, start_date=20240708T050430, end_date=20240708T050431
[2024-07-08T05:04:31.100+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T05:04:31.112+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T05:04:31.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
